name: Build Binaries

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

jobs:
  build-gcc:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: x86
          compiler: https://geometrydash.eu/_other/TDM-GCC-32.zip
        - name: x64
          compiler: https://geometrydash.eu/_other/TDM-GCC-64.zip

    name: Build ${{ matrix.config.name }}
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install TDM GCC 5.1.0
      run: |
        curl ${{ matrix.config.compiler }} -o compiler.zip -L
        7z x compiler.zip -o"C:/TDM-GCC-5.1.0"

    - name: Install Ninja
      run: |
        choco install ninja

    - name: Configure & Build
      run: |
        $env:PATH = "C:/TDM-GCC-5.1.0/bin;" + $env:PATH
        cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER=C:/TDM-GCC-5.1.0/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/TDM-GCC-5.1.0/bin/g++.exe -G Ninja -B build -S .
        cmake --build build --config Release

    - name: Move build to release folder
      run: |
        mkdir release
        mv build/CppShot.exe release/cppshot.exe

    - name: Grab Windows 98/2000 compatibility DLL
      if: matrix.config.name == 'x86'
      run: |
        curl https://github.com/Cvolton/CppShot/releases/download/v0.4/gdiplus.dll -o release/gdiplus.dll -L
        curl https://geometrydash.eu/_other/unicows.dll -o release/unicows.dll -L
    
    - name: Copy used licenses
      run: |
        cp C:/TDM-GCC-5.1.0/COPYING.winpthreads.txt ./release/

    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: cppshot-${{ matrix.config.name }}
        path: ./release/

  build-msvc:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: arm32

    name: Build ${{ matrix.config.name }}
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure & Build
      continue-on-error: true
      run: |
        cmake -G "Visual Studio 16 2019" -B build -DCMAKE_BUILD_TYPE=Release -A arm
        cmake --build build --config Release

    - name: Now we actually build
      run: |
        cmake --build build --config Release

    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: cppshot-${{ matrix.config.name }}
        path: ./build/Release/