name: Build Binaries

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

jobs:
  build-windows:
    name: Build Windows x86
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install TDM GCC 5.1.0
      run: |
        curl https://geometrydash.eu/_other/TDM-GCC-32.zip -o compiler.zip -L
        7z x compiler.zip -o"C:/TDM-GCC-5.1.0"

    - name: Install Ninja
      run: |
        choco install ninja

    - name: Configure & Build
      run: |
        $env:PATH = "C:/TDM-GCC-5.1.0/bin;" + $env:PATH
        cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER=C:/TDM-GCC-5.1.0/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/TDM-GCC-5.1.0/bin/g++.exe -G Ninja -B build -S .
        cmake --build build --config Release

    - name: Move build to release folder
      run: |
        mkdir release
        mv build/CppShot.exe release/cppshot.exe

    - name: Grab Windows 98/2000 compatibility DLL
      run: |
        curl https://github.com/Cvolton/CppShot/releases/download/v0.4/gdiplus.dll -o release/gdiplus.dll -L
        curl https://geometrydash.eu/_other/unicows.dll -o release/unicows.dll -L

    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: cppshot-x86
        path: ./release/